network.host: 0.0.0.0
# transport.host: 127.0.0.1
# http.host: 0.0.0.0
http.port: 9200
# network.publish_host: 127.0.0.1
# network.bind_host: 127.0.0.1
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.host: 0.0.0.0
transport.host: 127.0.0.1
